apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: telegram
type: Opaque
stringData:
  BOT_TOKEN: "8113326771:AAHd-PDuM1VvchLXTZkFrxmLzxsziwqMR_A"
  MOD_CHAT_ID: "<887760709>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: telegram
data:
  TOXICITY_URL: "http://toxicity-svc:8080/analyze"
  TOX_THRESHOLD: "0.5"
