apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: telegram-bot-pdb
  namespace: telegram
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: telegram-bot-svc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: toxicity-svc-pdb
  namespace: telegram
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: toxicity-svc
